authentication/authentication/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin

from django_yubico.views import login, password

urlpatterns = patterns(
    '',
    url(r'^login', login, name='yubico_django_login'),
    url(r'^password', password, name='yubico_django_password'),
)


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'authentication.authapp.views.index', name='index'),
    url(r'^upload/$', 'authentication.authapp.views.upload', name='upload'),
    url(r'^view/$', 'authentication.authapp.views.documents', name='documents'),
    url(r'^search/$', 'authentication.authapp.views.search', name='search'),
    url(r'^document/(?P<file_sha256>[0-9a-f]{64})/$', 'authentication.authapp.views.file_detail', name='file_detail'),
    url(r'^document/(?P<file_sha256>[0-9a-f]{64})/download/$', 'authentication.authapp.views.file_download', name='file_download'),
    url(r'^document/(?P<file_sha256>[0-9a-f]{64})/(?P<file_name>.*)\.sig$', 'authentication.authapp.views.file_signature', name='file_signature'),
    url(r'^admin/authapp/document/$', 'authentication.authapp.views.admin_document', name='admin_document'),
    url(r'^admin/login/', 'authentication.authapp.views.admin_login', name='admin_login'),
    #url(r'^admin/login', login, name='yubico_django_login'),
    url(r'^admin/password', password, name='yubico_django_password'),
    url(r'^admin/authapp/$', 'authentication.authapp.views.admin_authapp', name='admin_authapp'),
    url(r'^admin/authapp/document/add/$', 'authentication.authapp.views.add', name='add'),
    url(r'^admin/authapp/document/(?P<file_id>[0-9]+)/$', 'authentication.authapp.views.edit', name='edit'),
    url(r'^admin/logout', 'authentication.authapp.views.admin_logout', name='admin_logout'),
    url(r'^admin/auth/user/$', 'authentication.authapp.views.admin_user', name="admin_user"),
    url(r'^admin/auth/user/add/$', 'authentication.authapp.views.admin_user_add', name="admin_user_add"),
    url(r'^admin/auth/user/(?P<user_id>[0-9]+)/$', 'authentication.authapp.views.admin_user_edit', name="admin_user_edit"),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/authentication/authapp/models.py
from django.db import models
from authentication.authapp.crypto import sign, verify
from tempfile import NamedTemporaryFile
from datetime import datetime
import hashlib
import os
import internetarchive
from django.conf import settings

# Create your models here.
class Document(models.Model):
    doc_file = models.FileField(upload_to="%Y/%m")
    name = models.CharField(max_length=200, blank=True)
    #slug = models.SlugField()
    description = models.TextField(blank=True)
    license = models.TextField(blank=True)

    # filename: os.path.basename(doc_file.name)
    # filesize: doc_file.size

    sha256 = models.CharField(max_length=256, blank=True)
    sha512 = models.CharField(max_length=512, blank=True)
    gpgsig = models.TextField(blank=True)

    uploaded = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
      if self.name:
        return self.name
      else:
        return self.doc_file.url.split('/')[-1]

    def get_sig_url(self):
      return '/document/' + self.sha256 + '/' + os.path.basename(self.doc_file.name) + '.sig'

    def get_ia_url(self):
        url = "https://archive.org/download/"
        url += settings.IA_ITEM + '/'
        url += self.sha256
        url += os.path.splitext(self.doc_file.name)[1]
        return url

    @classmethod
    def sign_this_file(cls, sender, instance, created, **kwargs):
        """
        A callback that gets triggered after a `Document` is saved. Takes the
        file in `Document.doc_file` and runs it through `python-gnupg` (once
        the server is already configured) and saves a PGP signature to the
        `Document.gpgsig` field.
        """
        # Note that we don't care if it's `created` or not. When we upload
        # a new Document, let's sign it so we get a new GPG signature that
        # roughly corresponds with the `updated` timestamp.
        #
        # Use "update" instead of .save() so that we don't infinite-loop
        # and have the .post_save signal send over and over.
        # https://docs.djangoproject.com/en/1.7/ref/models/querysets/#update
        instance.doc_file.file.seek(0)
        Document.objects.filter(id=instance.id).update(gpgsig=sign(instance.doc_file.file.read()))

    @classmethod
    def save_filehashes(cls, sender, instance, created, **kwargs):
        instance.doc_file.file.seek(0)
        sha256 = hashlib.sha256()
        for chunk in iter(lambda: instance.doc_file.file.read(sha256.block_size), b''):
            sha256.update(chunk)
        sha_value = sha256.hexdigest()
        Document.objects.filter(id=instance.id).update(sha256=sha_value)

        instance.doc_file.file.seek(0)
        sha512 = hashlib.sha512()
        for chunk in iter(lambda: instance.doc_file.file.read(sha512.block_size), b''):
            sha512.update(chunk)
        Document.objects.filter(id=instance.id).update(sha512=sha512.hexdigest())
        Document.export_to_ia(instance, sha_value)

    def export_to_ia(self, sha_value, **kwargs):
        """
        Called after a `Document` is signed and the hashes are calculated. Takes the
        file in `Document.doc_file` and uploads it to the internetarchive with the sha256 value as the
        filename.
        """
        item = internetarchive.Item(settings.IA_ITEM)
        md = dict(creator=settings.IA_CREATOR)
        key = sha_value + os.path.splitext(self.doc_file.name)[1]
        item.upload_file(self.doc_file, key=key, metadata=md, access_key=settings.IA_ACCESS_KEY, secret_key=settings.IA_SECRET_KEY)

    def test_user_file(self, uploaded_fp):
        """
        Given a user-uploaded file and this object (self), cryptographically
        compare the user file against the GPG signature for this version
        of the file.

        At this point, we should be pretty sure it's the same file. (Filename, size,
        hash, something that isn't CPU expensive like GPG.)
        """
        # Assume that "uploaded_file" is a file pointer that hasn't
        # been handled yet. Can be in memory or a Django-controlled temp file,
        # we'll write it out to a file that we control just to be sure
        # (so that we can call gpg against this filename).
        # https://docs.djangoproject.com/en/1.7/topics/http/file-uploads/#basic-file-uploads

        # Write the uploaded file to disk, using a `tempfile`
        upload_tmp = NamedTemporaryFile('wb+', delete=False)
        upload_tmpfp = upload_tmp.file
        for chunk in uploaded_fp.chunks():
            upload_tmpfp.write(chunk)
        upload_tmpfp.close()

        # now we can get path to the file we just wrote on disk
        uploaded_file_path = upload_tmp.name

        # Write our gpgsig to a file on disk (<filename>.asc)
        sig_file_path = "%s.asc" % uploaded_file_path
        sigfp = open(sig_file_path, 'wb+')
        sigfp.write(self.gpgsig)
        sigfp.close()

        # do the crypto
        result = verify(uploaded_file_path, sig_file_path)

        # Clean up after ourselves and remove the user's uploaded file.
        if os.path.exists(uploaded_file_path):
            os.unlink(uploaded_file_path)

        # print "User's file matches Agency file %s. File was signed by '%s' (key ID %s) on %s UTC and cryptographically matches the user's file." % (
        #   os.path.basename(self.doc_file.name),
        #   result.username,
        #   result.key_id,
        #   datetime.fromtimestamp(float(result.timestamp)).strftime("%Y-%m-%d %H:%I:%S")
        # )

        # result attrs: username, valid (True or False), timestamp (str of
        # unix timestamp), key_id, and a few others.
        return result

    @staticmethod
    def find_user_file(uploaded_fp):
        """
        Given a user file (via upload), hash the file's data with SHA512
        and then look for a `Document` object that matches that hash.

        We could stand to make this fuzzier / smarter, since we'll be checking
        any matches we get here with GPG.
        """
        h512 = None
        sha512 = hashlib.sha512()
        for chunk in iter(lambda: uploaded_fp.read(sha512.block_size), b''):
            sha512.update(chunk)
        h512 = sha512.hexdigest()

        results = Document.objects.filter(sha512=h512)

        uploaded_fp.seek(0)

        return results

models.signals.post_save.connect(Document.sign_this_file, sender=Document)
models.signals.post_save.connect(Document.save_filehashes, sender=Document)

authentication/authentication/authapp/templates/authentication/_base.html
{% load static %}<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <link href="{% static 'authentication/css/dropzone.css' %}" type="text/css" rel="stylesheet"/>
  <link href="{{ STATIC_URL }}authentication/bootstrap-3.1.1-dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="{{ STATIC_URL }}authentication/css/starter-template.css" rel="stylesheet">
  <script src="{{ STATIC_URL }}authentication/js/jquery-1.11.1.min.js"></script>
  <script src="{{ STATIC_URL }}authentication/bootstrap-3.1.1-dist/js/bootstrap.min.js"></script>

  <title>{% block title %}DC Council DataSeal{% endblock %}</title>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    {% if user.is_authenticated %}
      <a class="navbar-brand" href="/admin/authapp/">DC Council DataSeal</a>
    {% else %}
      <a class="navbar-brand" href="/">DC Council DataSeal</a>
    {% endif %}
    </div>
    
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/upload/">Check File</a></li>
        <li><a href="/view/">Get List of Hash Values</a></li>
        {% if user.is_authenticated %}
        <li><a href="/admin/authapp/document/add/">Add File</a></li>
        <li><a href="/admin/authapp/document/">View All</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
      {% if user.is_staff %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/auth/user">Edit Users</a></li>
            <li class="divider"></li>
            <li><a href="/admin/logout/">Log out</a></li>
          </ul>
        </li>
      {% elif user.is_authenticated %}
        <li><a href="/admin/logout/">Log out</a></li>
      {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
    
  </div>
</div>

<div class="container">
  {% block body %}{% endblock %}
</div><!-- /.container -->

</body>
</html>

authentication/authentication/authapp/templates/authentication/add.html
{% extends "authentication/_base.html" %}
{% load static %} <!DOCTYPE html>
{% block title %}Authentication.io Add File {% endblock %}

{% block body %}
  
  <!-- Custom styles for this template -->
  <link href="{{ STATIC_URL }}authentication/css/add.css" rel="stylesheet">

  <div class="container">
  <form class="form-horizontal form-document" role="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% block description %} 
      <h2 class="form-document-heading">Add a file</h2>
    {% endblock %}
    {% for field in form %}
    {% if field.field.required %}
      <div class="form-group">
        {{ field.errors }}
        <label for="id_{{field.id_for_label}}" class="col-sm-2 control-label">
        {{field.label}}
        </label>
        <div class="col-sm-10">
          {{ field }}
        </div>
      </div>
    {% endif %}
    {% endfor %}

<div class="panel panel-default">
<div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#DocInfo">
<h4 class="panel-title">
Additional Information (Optional)
<b class="caret"></b>
</h4>
</div>
<div id="DocInfo" class="panel-collapse collapse">
<div class="panel-body">
    {% for field in form %}
    {% if not field.field.required %}
      <div class="form-group">
        {{ field.errors }}
        <label for="id_{{field.id_for_label}}" class="col-sm-2 control-label">
        {{field.label}}
        </label>
        <div class="col-sm-10">
          {{ field }}
        </div>
      </div>
    {% endif %}
    {% endfor %}
</div>
</div>
</div>

    {% block hashes %}{% endblock %}
    <button class="btn btn-lg btn-primary" type="submit">
    {% block action %}Submit{% endblock %}
    </button>
  </form>
  </div> <!-- /container -->
{% endblock %}

authentication/authentication/authapp/templates/authentication/admin_authapp.html
{% extends "authentication/_base.html" %}
{% load static %}

{% block body %}

  <h1> Documents </h1>

  <a class="btn btn-default" href="/admin/authapp/document/">View All Documents</a>
  <a class="btn btn-default" href="/admin/authapp/document/add/">Add New Document</a>


{% endblock %}

authentication/authentication/authapp/templates/authentication/admin_login.html
{% load static %} <!DOCTYPE html>
<html smlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}Authentication.io login {% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ STATIC_URL}}authentication/bootstrap-3.1.1-dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{{ STATIC_URL }}authentication/css/signin.css" rel="stylesheet">

</head>

<body>
  <div class="container">
<!--   <form class="form-signin" role="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <h2 class="form-signin-heading">Please sign in</h2>
    
    {% for field in form %}
      <div class="fieldWrapper">
        {{ field.errors }}
        <input id="{{ field.id }}" 
               maxlength="{{ field.maxlength }}" 
               name="{{ field.name }}" 
               type="{{ field.name }}" 
               placeholder="{{ field.name }}" 
               type="{{field.name }}" 
               class="form-control" 
               required
        >
      </div>
    {% endfor %}
    
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
 -->

<div id="yubikey_login">
<form action="" method="post" onkeypress="return event.keyCode != 13" id="yubico_form">{% csrf_token %}
{{ form.as_p }}
<p><input type="submit" id="yubikey_login_button" value="Log in" /></p>
</form>
</div>

  </div> <!-- /container -->
</body>
</html>

authentication/authentication/authapp/templates/authentication/admin_user_add.html
{% extends "authentication/_base.html" %}
{% load static %} <!DOCTYPE html>
{% block title %}Authentication.io {{ action }} User {% endblock %}

{% block body %}
  
  <!-- Custom styles for this template -->
  <link href="{{ STATIC_URL }}authentication/css/add.css" rel="stylesheet">

  <div class="container">
  <form class="form-horizontal form-document" role="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% block description %} 
      <h2 class="form-document-heading">{{action}} a user</h2>
    {% endblock %}
    {% for field in form %}
    {% if field.field.required %}
      <div class="form-group">
        {{ field.errors }}
        <label for="id_{{field.id_for_label}}" class="col-sm-2 control-label">
        {{field.label}}
        </label>
        <div class="col-sm-10">
          {{ field }}
        </div>
      </div>
    {% endif %}
    {% endfor %}

<div class="panel panel-default">
<div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#DocInfo">
<h4 class="panel-title">
Additional Information (Optional)
<b class="caret"></b>
</h4>
</div>
<div id="DocInfo" class="panel-collapse collapse">
<div class="panel-body">
    {% for field in form %}
    {% if not field.field.required %}
      <div class="form-group">
        {{ field.errors }}
        <label for="id_{{field.id_for_label}}" class="col-sm-2 control-label">
        {{field.label}}
        </label>
        <div class="col-sm-10">
          {{ field }}
        </div>
      </div>
    {% endif %}
    {% endfor %}
</div>
</div>
</div>

    <button class="btn btn-lg btn-primary" type="submit">
    {% block action %}Submit{% endblock %}
    </button>
  </form>
  </div> <!-- /container -->
{% endblock %}

authentication/authentication/authapp/templates/authentication/document.html
{% extends "authentication/_base.html" %}
{% load static %}

{% block body %}
  <link href="{{ STATIC_URL }}authentication/DataTables-1.10.0/media/css/jquery.dataTables.css" rel="stylesheet">
  <script src="{{ STATIC_URL }}authentication/DataTables-1.10.0/media/js/jquery.dataTables.min.js"></script>
  <link href="{{ STATIC_URL }}authentication/css/document.css" rel="stylesheet">

  <h1> Documents </h1>
  <a class="btn btn-lg btn-primary" href="/admin/authapp/document/add/">Add new document</a>

  <table name="documents" id="documents">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date Added</th>
        <th>Date Updated</th>
        <th class="text-center">Delete?</th>
      </tr>
    </thead>
    <tbody>
      {% for doc in documents %}
      <tr id="row{{ doc.id }}">
        <td><a href="/admin/authapp/document/{{ doc.id }}">{{ doc }}</a></td>
        <td>{{ doc.uploaded }}</td>
        <td>{{ doc.updated }}</td>
        <td><button class = "btn center-block" data-toggle="modal" data-target="#deleteForm{{ doc.id }}"><span class="glyphicon glyphicon-remove"></span></button></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <!------------------Delete Form--------------------- -->
  {% for doc in documents %}
    <div class="modal fade" id="deleteForm{{ doc.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
          </div>
          <div class="modal-body">
            Are you sure you want to delete {{ doc }}?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <form role="form" method="post" enctype="multipart/form-data" class="form form-inline" name={{ doc.id }}> 
              {% csrf_token %}
              <input type="text" name="doc_id" class = "hidden" value="{{doc.id }}">
              <button type="submit" value= "Submit" class="btn btn-primary">Confirm</button> 
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
<!--------------------------------------- -->
<script>
  $(document).ready(function() {
    oTable = $('#documents').dataTable( {
        "oLanguage": { "sSearch": ""}
    });
    $('div.dataTables_filter input').addClass('form-control').attr("placeholder", "Search");

    $('.form').submit(function(event) {
        event.preventDefault();
        doc_id = $(this).attr('name')
        $.ajax({
          url: "/admin/authapp/document/",
          type: "POST",
          data: $(this).serialize(),
          success: function(data) {
            $('#deleteForm'+doc_id).modal('hide');
            oTable.fnDeleteRow($('#row'+doc_id));
          }
        });
    });

  } );
</script>

{% endblock %}

authentication/authentication/authapp/templates/authentication/documents.html
{% extends "authentication/_base.html" %}
{% load static %}

{% block body %}
  <link href="{{ STATIC_URL }}authentication/DataTables-1.10.0/media/css/jquery.dataTables.css" rel="stylesheet">
  <script src="{{ STATIC_URL }}authentication/DataTables-1.10.0/media/js/jquery.dataTables.min.js"></script>
  <link href="{{ STATIC_URL }}authentication/css/document.css" rel="stylesheet">

  <h1> Check the Hash Values for Documents </h1>
  <table name="documents" id="documents">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date Added</th>
        <th>Date Updated</th>
        <th>SHA256</th>
        <th>Download .sig</th>
<!-- TO ADD:
        <th>SHA512</th> 
-->
      </tr>
    </thead>
    <tbody>
      {% for doc in documents %}
      <tr id="row{{ doc.sha256 }}">
<!--        <td><a href="/document/{{ doc.id }}">{{ doc }}</a></td> -->
        <td><a href="{{doc.get_ia_url}}">{{ doc }}</a></td>
        <td>{{ doc.uploaded }}</td>
        <td>{{ doc.updated }}</td>
        <td>{{ doc.sha256 }}</td>
        <td><a href="{{ doc.get_sig_url }}">Signature</a></td>
<!-- TO ADD:
        <td>{{ doc.sha512 }}</td> 
-->
      </tr>
      {% endfor %}
    </tbody>
  </table>

<script>
  $(document).ready(function() {
    oTable = $('#documents').dataTable( {
        "oLanguage": { "sSearch": ""}
    });
    $('div.dataTables_filter input').addClass('form-control').attr("placeholder", "Search");

    $('.form').submit(function(event) {
        event.preventDefault();
        doc_id = $(this).attr('name')
        $.ajax({
          url: "/admin/authapp/document/",
          type: "POST",
          data: $(this).serialize(),
          success: function(data) {
            $('#deleteForm'+doc_id).modal('hide');
            oTable.fnDeleteRow($('#row'+doc_id));
          }
        });
    });

  } );
</script>

{% endblock %}

authentication/authentication/authapp/templates/authentication/edit.html
{% extends "authentication/add.html" %}
{% load static %} <!DOCTYPE html>

{% block title %}Authentication.io Edit File {% endblock %}

{% block description %}
  <h2 class="form-document-heading">Edit a file</h2>
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
{% endblock %}

{% block hashes %}

<div class="panel panel-default">
  <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#HashInfo">
    <h4 class="panel-title">
      Hash Data
      <b class="caret"></b>
    </h4>
  </div>

  <div id="HashInfo" class="panel-collapse collapse">
    <div class="panel-body">
      <div class="form-horizontal">
        
        <div class="form-group">
          <label for="id_sha256" class="col-sm-2 control-label">Sha256</label>
            <div class="col-sm-10">
              <input type="text" id="id_sha256" class="form-control" value={{doc.sha256}} readonly>
              </input>
            </div>
          </div>

          <div class="form-group">
            <label for="id_sha512" class="col-sm-2 control-label">Sha512</label>
              <div class="col-sm-10">
               <input type="text" id="id_sha512" class="form-control" value={{doc.sha512}} readonly>
               </input>
             </div>
           </div>
    
           <div class="form-group">
             <label for="id_gpgsig" class="col-sm-2 control-label">Gpgsig</label>
               <div class="col-sm-10">
                 <textarea id="id_gpgsig" class="form-control" readonly>{{doc.gpgsig}} 
                 </textarea>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>

{% endblock %}

{% block action %} Save Changes {% endblock %}

authentication/authentication/authapp/templates/authentication/upload.html
{% extends "authentication/_base.html" %}
{% load static %}

<!DOCTYPE html>

{% block title %}Authentication.io: Check a File{% endblock %}
{% block body %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'authentication/css/dropzone.css' %}" type="text/css" rel="stylesheet" />
  <link href="{{STATIC_URL}}authentication/css/edit.css" rel="stylesheet" />
  <style>
    .row{word-wrap: normal;   
      }
  </style>


<div class="container">
    <h1>Drag-and-drop a file to confirm whether it's authentic!</h1>
    <div id="formid">
        <form id="dz" class="dropzone" enctype="multipart/form-data" method="post" action="{% url 'upload' %}">
            {% csrf_token %}
        </form>
    </div>
    <div id="response">

    </div>
    <div class="panel panel-default hidden">
      <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#FileInfo">
        <h4 class="panel-title">File Details <b class="caret"></b></h4>
      </div>
      <div id="FileInfo" class="panel-collapse collapse">
        <div class="panel-body" id="details">
          <div class="form-horizontal">
          
          <div class="form-group">
            <label for="doc_name" class="col-sm-2 control-label">Document Name:</label>
            <div class="col-sm-10">
              <input type="text" id="doc_name" class="form-control" readonly></input>
            </div>
          </div>

          <div class="form-group">
            <label for="id_sha512" class="col-sm-2 control-label">SHA512:</label>
            <div class="col-sm-10">
              <input type="text" id="id_sha512" class="form-control" readonly></input>
            </div>
            </div>
          
          <div class="form-group">
            <label for="fingerprint" class="col-sm-2 control-label">Signer Fingerprint:</label>
            <div class="col-sm-10">
              <input type="text" id="fingerprint" class="form-control" readonly></input>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
<script src="{% static 'authentication/js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'authentication/js/dropzone.js' %}"></script>
<script type="text/javascript">
Dropzone.options.dz = {
    paramName: "user_file",
    init: function() {
        this.on("success", function(file) {
            r = JSON.parse(file.xhr.response);
            d = r.document;
            v = r.validation;
            if (v && v.is_valid == true) {
                $("#response").html("<h2 style='color:green'><span class='glyphicon glyphicon-ok'></span> File found!</h1>");
                $("#doc_name").attr("value", d.name);
                $("#id_sha512").attr("value", d.sha512);
                $("#fingerprint").attr("value", v.fingerprint);
                $(".panel.hidden").removeClass('hidden');
            }
            else {
              $("#response").html("<h2 style='color:crimson'><span style='color:crimson' class='glyphicon glyphicon-remove'></span> File does not match any documents</h2>");
              $(".panel").addClass('hidden');
            }
            this.removeFile(file)
        });
    }
}
</script>
{% endblock %}